ticket_price: 1
tax_percentage: 0
timer: 120
loser_broadcast: '&e%WINNER%&bさんがジャックポットで&e%PERCENTAGE%%&bの確立で&c&l&n￥%AMOUNT%&eを勝ち取りました！'
winner_broadcast: '&4&l&lおめでとうございます！ あなたはジャックポットで &e%PERCENTAGE%%&4&lの確立で &c&l￥%AMOUNT% &e&l勝利しました！税引き後(税引き後￥%TAXED%)'
mysql:
  host: localhost
  port: 3306
  user: root
  pass: password
  db: man10jackpot